<?php

declare(strict_types=1);

namespace Dodopayments\LicenseKeys\LicenseKey;

/**
 * The source of the license key - 'auto' for keys generated by payment/subscription flows, 'import' for merchant-imported keys.
 */
enum Source: string
{
    case AUTO = 'auto';

    case IMPORT = 'import';
}
