name: Release Doctor
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  release_doctor:
    name: release doctor
    runs-on: ubuntu-latest
    if: github.repository == 'dodopayments/dodopayments-php' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || startsWith(github.head_ref, 'release-please') || github.head_ref == 'next')

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check release environment
        run: |
          bash ./bin/check-release-environment
        env:
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          PACKAGIST_USERNAME: ${{ secrets.DODO_PAYMENTS_PACKAGIST_USERNAME || secrets.PACKAGIST_USERNAME }}
          PACKAGIST_SAFE_KEY: ${{ secrets.DODO_PAYMENTS_PACKAGIST_SAFE_KEY || secrets.PACKAGIST_SAFE_KEY }}
